[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "pnpx", args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "typescript",
] }
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "eslint",
]

[[language]]
name = "svelte"
auto-format = true
formatter = { command = "pnpx", args = [
  "prettier",
  "--config",
  ".prettierrc",
  "--parser",
  "svelte",
] }
language-servers = [
  { name = "svelteserver", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
]
file-types = ["svelte"]
