name: Release Workflow

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release

  release-assets:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Package source
        id: package-source
        run: zip -r katei-src.zip .

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build

      - name: Package
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: build
          filename: "{name}-{version}.xpi"

      - uses: yayuyokitano/firefox-addon@v0.0.3-alpha
        with:
          api_key: ${{ secrets.AMO_ISSUER }}
          api_secret: ${{ secrets.AMO_SECRET }}
          guid: 'katei@ixora-0'
          xpi_path: ${{ steps.web-ext-build.outputs.target }}
          src_path: katei-src.zip

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ${{ steps.web-ext-build.outputs.target }}
